# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Release

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          # We need to fetch all branches and commits so that Nx affected has a base to compare against.
          fetch-depth: 0
      - uses: nrwl/nx-set-shas@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install
      - run: pnpm exec nx affected -t test --pararllel=3
      - run: pnpm exec nx affected -t build --pararllel=3
      - run: |
          npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
          pnpm exec nx affected -t publish --pararllel=3
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}